### ISSUE TITLE
1.2.1 - **Inicio de sesión - Maquetado HTML.**

### ISSUE THREAD

**Issue by frankynztein** [RocioAl/LIM009-Social-Network#4]
En etiqueta header:
- [x] figure, img: Imagen de encabezado.

En etiqueta main:
- [x] h1: Nombre de la red social.
- [x] h2: Bienvenida general.
- [x] Input type email.
- [x] Input type password.
- [x] Botón Log in.
- [x] p: O bien ingresa con...
- [x] figure, img: Logos de Facebook y Google.

En etiqueta footer:
- [x] p: ¿No tienes una cuenta.
- [x] a: Regístrate.

**Comment by frankynztein** [comment]
Pendientes:

- Definir el nombre de la red social (mantuve el tema sobre opiniones de lugares de comida y por eso usé esa imagen en el header, igual se puede modificar).

**Comment by NardaC** [comment]
claro, creo q nos quedamos con esa idea, de hacer 2 registros para empresa y para usuario? o solo será para comensales o usuarios.

**Comment by NardaC** [comment]
no se olviden de trabajar en un rama, para luego fusionar nuestros códigos en la rama principal de la dueña del repo.!
